Projectile spells
goudanough/WizARds pull request #14
Opened 2024-02-09 12:58 UTC by AmosHolland

This branch has a few things in it.

Voice recognition:
- Use a vosk model to recognise spoken word
- Use hand gestures to enable / disable voice recognition
- Do something in the game responding to voice recognition 

Projectiles:
- spawn projectiles with properties
- update projectiles based on their velocity
- detect collisions between projectiles and surfaces, and react to them

Spell casting:
- combine voice recognition and projectiles to allow for rudimentary spellcasting

This code will need to be updated to properly integrate with rollback and other systems.

2024-02-12 10:35 UTC, rosefromthedead requested changes
Other than formatting, LGTM, thanks. I'll rustfmt this and push a commit on top of what you have, please turn on "format on save" in your editors

2024-02-14 10:14 UTC, AmosHolland commented on src/spell_control.rs
> +*/
It's dead, now removed :+1:

2024-02-14 10:14 UTC, AmosHolland commented
This is working in single player, but we haven't had success with multiplayer yet. If we need to push this through for the sake of the demo it will work for that.

2024-02-15 14:05 UTC, OwenBoisse requested changes
we now have a zipped vosk-model in order to bake the model into the apk, therefore we need to remove the original vosk-model folder

2024-02-15 14:15 UTC, Foxinatel requested changes
- Remove `build.rs` if it's unnecessary
- Remove the file called `grep` which contains the output of `iw --help`
- Move `/src/vosk-model.zip` to a directory that isn't `/src`
- Remove unused function `spawn_vr_camera` and struct `VRCamera`
- Clean up some remaining cargo clippy lints

2024-02-15 14:28 UTC, LICHENGWEI-cloud commented
the visual effect works well for me. When I say the colour word and hold the exact gesture. the ball corresponding to that colour is generated on my right hand correctly. And the ball will be emitted when I hold the gesture corresponding to the emission action.

2024-02-15 14:55 UTC, AmosHolland commented
> * Remove `build.rs` if it's unnecessary
> 
>     * Remove the file called `grep` which contains the output of `iw --help`
> 
>     * Move `/src/vosk-model.zip` to a directory that isn't `/src`
> 
>     * Remove unused function `spawn_vr_camera` and struct `VRCamera`
> 
>     * Clean up some remaining cargo clippy lints

I believe these are now done. Some linting issues are still there, but these are about unused imports that are actually used when we run on the headset.

2024-02-15 14:56 UTC, AmosHolland commented
> We now have a zipped vosk-model in order to bake the model into the apk, therefore we need to remove the original vosk-model folder.

This is done now.

2024-02-15 14:58 UTC, YiwenLiang-0-0 approved these changes
Voice recognition and spells projectile works well. In the test, can control whether to recognize voice based on gestures, generate balls of different colors based on different spells, and launch them through gestures.

2024-02-15 15:05 UTC, OwenBoisse approved these changes
Looks all good 👍

2024-02-15 15:13 UTC, rosefromthedead approved these changes
Get that shit merged

2024-02-15 15:15 UTC, Foxinatel approved these changes
I support the LGTM community and approve their changes

2024-02-15 15:15 UTC, merged