Device discovery
goudanough/WizARds pull request #15
Opened 2024-02-12 11:32 UTC by Foxinatel

This PR implements the following network flow diagram: ![networking flow diagram](https://media.discordapp.net/attachments/1183807789328502805/1205136796212797512/image.png?ex=65d7461a&is=65c4d11a&hm=678c98f71279ad1fbbfe88e9f17ee1357547a1c1eabb74280dffa3eb1bf8c068&=&format=webp&quality=lossless&width=853&height=1089)

Allowing GGRS sessions to be created over a local network using multicast-based device discovery

2024-02-12 11:36 UTC, Foxinatel commented
A few features are missing from this PR:
- Being able to select at runtime whether you want to host or join. Ideally this will be done with a UI, which needs some further consideration
- Anchor sharing, as this relies on foundational code from the `scene-v2` branch and also doing developer verification through Meta

2024-02-20 18:55 UTC, Foxinatel commented
I'm going to temporarily close this PR for now. It may be re-opened in future.
While this branch does work, we've decided that for the purposes of our tech demo we want to just have a single-player game
Also, this branch isn't particularly useful until we can figure out how to create interactable menus so the player can select whether they want to host or join

2024-02-22 09:49 UTC, rosefromthedead commented
reopening to keep it in the tracker, i'll mark as draft if i can figure out how

2024-03-06 13:44 UTC, Foxinatel commented
This branch is nearly ready for review now. Before reopening this commit I would like the following PRs to land, as this code depends on both of these:
- #46
- https://github.com/goudanough/bevy_oxr/pull/5

One extra thing to consider as well is that currently we panic immediately if we're on a network that doesn't let us establish a multicast. We should probably add some visual indicators or something explaining what's gone wrong.

2024-03-14 08:40 UTC, AmosHolland commented on src/network.rs
> +const GGRS_PORT: u16 = 47511;
based.

2024-03-14 09:03 UTC, AmosHolland requested changes
Overall looks good, really good annotations as well, I think I could actually follow what was happening. 

Should we move network.rs into the network folder, and just have it as `mod.rs` in there? Just seems odd to have a network.rs and a network folder.

2024-03-14 09:03 UTC, AmosHolland commented on src/network.rs
> +        // TODO: put this on a timer
If adding a timer wouldn't take very long should we do it now? I can imagine this getting merged, and then after that we never look at it again so we never fix this on a timer and we're just sending out multicast messages during every frame of setup forever.

2024-03-14 13:35 UTC, Foxinatel commented on src/network.rs
> +        // TODO: put this on a timer
Fixed with https://github.com/goudanough/WizARds/pull/15/commits/5a01b76ac60e37e428b6b8858e3ca60380e23157

2024-03-14 15:11 UTC, AmosHolland approved these changes
Looks good, nice work!

2024-03-20 09:13 UTC, AmosHolland requested changes
looks good, minor change to ticking the timer.

2024-03-20 09:13 UTC, AmosHolland commented on src/network/mod.rs
> +    timer.0.tick(time.delta());
If we're only checking the timer in once place I think the best way to do this is
```rust
if (...) { ...
} else if timer.0.tick(time.delta()).just_finished() { ... }

2024-04-15 10:31 UTC, rosefromthedead commented
Please undo the Cargo.lock changes (other than the bevy_oxr update ofc). There's a lot of speech changes in here, are they supposed to be? Especially the addition of grammar = ["fireball", "lightning"], I think some other changes have made their way in by accident

2024-04-15 17:43 UTC, Foxinatel commented
Yeah I think the best course of action for this PR is just to close it, because there were some half-baked stuff that got changed and/or reverted in `anchor-sync`

2024-04-15 17:44 UTC, closed without merging