Boss AI state machine
goudanough/WizARds pull request #16
Opened 2024-02-12 14:32 UTC by YiwenLiang-0-0

Three states of the boss are implemented.

When the boss is far enough away from the player (greater than 20), the boss is the default target player; 2. When the distance becomes closer (10-20), the boss will move towards the player; 3. The boss is close enough to the player (less than or equal to 10), and the boss will move into attack state.

2024-02-16 15:30 UTC, AmosHolland requested changes
Mostly minor changes to make the boss code work better with out existing code. 

The update to boss_attack is significant, but shouldn't take long, as most of the logic in boss_attack is handled by projectiles. (If you have any questions about using the projectile system let me know!)

2024-02-16 15:30 UTC, AmosHolland commented on src/boss.rs
> +//     commands.spawn(TextBundle {
As far as I know regular Bevy UI stuff isn't going to work in AR, so we can just delete this commented block

2024-02-16 15:30 UTC, AmosHolland commented on src/boss.rs
> +        // Health(BOSS_MAX_HEALTH),
Why is this commented out? If rust complains about health being unused or something that should be fine. Ideally the boss should have a health component.

2024-02-16 15:30 UTC, AmosHolland commented on src/boss.rs
> +    if let Some(player_transform) = player_query.iter().next() {
In multiplayer I think this will just target whatever player is first in the query, this might need to be changed for multiplayer to work completely, but since we're going for a singleplayer demo it might be fine to keep it this way, though I'm not certain. I would be interested in a second opinion.

2024-02-16 15:30 UTC, AmosHolland commented on src/boss/boss_attack.rs
> +use bevy::{
I think this should be updated to use the same projectile system as spellcasting, (the one in projectile.rs), just so that any changes to projectile logic apply everywhere. You can look in spell_control.rs for an example on how to spawn projectiles in the projectile system.

2024-02-16 15:30 UTC, AmosHolland commented on src/player.rs
> +        RigidBody::Dynamic,
The player should have a Kinematic RigidBody, instead of a Dynamic one, since we only want the player to be moved when we specifically want them to be,

2024-02-16 15:30 UTC, AmosHolland commented on src/player.rs
> +        PbrBundle {
Now that we're in AR development we might not want to spawn a visible object on the player, since it might block them from seeing their actual body / hands.

2024-02-16 15:30 UTC, AmosHolland commented on src/player.rs
> +        ShapeCaster::new(
Since we're now in AR I don't think we need to cast the players collider down to the floor, it should instead be based on the position of their head and hands (which is a little bit what was being worked on in hitbox).

2024-02-16 15:30 UTC, AmosHolland commented on src/lib.rs
> +            mesh: meshes.add(Mesh::from(shape::Plane::from_size(128.0))),
I would prefer we modify the size of plane_mesh, instead of using a different sized mesh for the floor's collider and it's visual components. (i.e. define plane_mesh to be of size 128.0, then use plane_mesh here)

2024-02-16 15:38 UTC, YiwenLiang-0-0 commented on src/boss.rs
> +//     commands.spawn(TextBundle {
ok will delete it

2024-02-16 15:41 UTC, YiwenLiang-0-0 commented on src/boss.rs
> +    if let Some(player_transform) = player_query.iter().next() {
yes i agree, if we have multiplayers the boss need to select one player to attack and target.

2024-02-16 15:54 UTC, YiwenLiang-0-0 commented on src/player.rs
> +        PbrBundle {
the playerplugin is not use in AR mode right now, just have used it to test in pancake mode, will delete it.

2024-02-16 16:08 UTC, YiwenLiang-0-0 commented on src/lib.rs
> +            mesh: meshes.add(Mesh::from(shape::Plane::from_size(128.0))),
ok will use plane_mesh instead it

2024-02-17 13:12 UTC, AmosHolland commented on src/boss/boss_attack.rs
> +use bevy::{
This is done!

2024-02-17 13:15 UTC, AmosHolland approved these changes
All looks good now - this will likely need a refactor at some point - the code is spread out between more files is needed, but it's okay for the demo.

2024-02-17 13:32 UTC, YiwenLiang-0-0 reviewed
Looks all good! The fonts asset is not use right now if it is usable for the future we can keep it.

2024-02-17 13:41 UTC, AmosHolland commented
> Looks all good! The fonts asset is not use right now if it is usable for the future we can keep it.

good catch! I'll remove the font asset as well.

2024-02-18 14:02 UTC, OwenBoisse approved these changes
looks all good 👍

2024-02-18 14:15 UTC, merged