Decouple spell casting from speech controls
goudanough/WizARds pull request #46
Opened 2024-03-05 21:44 UTC by Foxinatel

Addresses #44
This commit decouples the logic for spell casting from the game logic. This gives us extra granularity that allows us to much more easily reuse the speech plugin from other parts of the code, which can be used for things like menus.

2024-03-06 10:00 UTC, AmosHolland requested changes
This all looks good, as long as it's tested and working as intended I'm happy to make this change. Just have to wait for the updated controls to be integrated and then I'll be happy to merge.

2024-03-07 10:47 UTC, AmosHolland commented
Looking at the new controls code this is going to need *significant* changes to integrate properly. In the new controls there's no defined point where recording stops, instead recording stops when the recogniser successfully recognises a word from it's grammar, just as a heads up.

2024-03-07 18:36 UTC, Foxinatel commented
So the new system for managing speech and spell casting has been implemented, although this still poses some major conflicts. Instead of expensively storing our own buffer for audio data with large copies happening whenever we want to detect a word, we now stream the data into the vosk model in small snippets. This also allows us to make small partial queries to our model to see if it has detected a word since recording began.

Since this change from storing data to streaming it should implement a lot of the work done manually in #47, I think the ideal solution from here is to place a block on that PR until the remaining features become supported in this branch.

2024-03-08 14:26 UTC, Foxinatel commented
We ball, the new spell casting system is fully implemented into the new speech system

2024-03-12 09:20 UTC, rosefromthedead commented on src/spells.rs
> +fn track_spell_indictator(
optional: indictator -> indicator

2024-03-12 09:20 UTC, rosefromthedead approved these changes
LGTM, thanks!

2024-03-12 10:24 UTC, AmosHolland approved these changes

2024-03-12 10:24 UTC, AmosHolland commented on src/spell_control.rs
> +}
This function is defined twice, once here, and once in speech.rs, do we need to do this? Could we not just make one of them public?

2024-03-12 10:25 UTC, AmosHolland commented
Overall LGTM!

2024-03-12 10:27 UTC, rosefromthedead requested changes
Amos is so right, blocking this until `check_fingers_close` is dedup'd, otherwise someone's gonna have a hard time figuring out why changing the code in one of them has no effect on the callsite of the other

2024-03-12 15:29 UTC, Foxinatel commented on src/spell_control.rs
> +}
Yeah I was a little unsure about what to do with that. This decoupling means that the casting doesn't necessarily need to be the same action as stopping the recording. I think the shout is to put it in `speech.rs` as public.

2024-03-12 15:42 UTC, Foxinatel commented on src/spells.rs
> +fn track_spell_indictator(
fixed in most recent commit

2024-03-12 15:43 UTC, AmosHolland approved these changes
de-duping the function makes sense, lgtm!

2024-03-12 16:59 UTC, Foxinatel commented
Had a bit of a nightmare getting these commits orderly, as this branch used commits from Alyssa that got redone, making this branch try to pull in a bunch of dead commits

2024-03-13 09:52 UTC, rosefromthedead commented on src/spell_control.rs
> +}
Girl

2024-03-14 08:09 UTC, AmosHolland approved these changes
Looks good!

2024-03-14 15:12 UTC, AmosHolland approved these changes
Looks good!

2024-03-15 11:42 UTC, rosefromthedead approved these changes
I'm like semi conscious, but lgtm. Congrats on the narrowly negative diffstat :)

2024-03-19 16:11 UTC, OwenBoisse approved these changes
tested and lgtm

2024-03-20 09:09 UTC, AmosHolland approved these changes
still looks good!

2024-03-20 09:14 UTC, merged