New controls
goudanough/WizARds pull request #47
Opened 2024-03-06 10:21 UTC by OwenBoisse

add new temporary controls involving:
- putting thumbs and index fingers together to select spell
- not having to stop recording for spell to be chosen
- firing by pulling hands apart
- aiming with head

2024-03-07 10:44 UTC, AmosHolland requested changes
Some minor nitpicks to make this more readable, overall this looks good, and we know that it works.

2024-03-07 10:44 UTC, AmosHolland commented on src/spell_control.rs
> +pub struct PalmMidPoint(pub Vec3);
Could we rename this to `PalmsMidPont`? When I first read this I thought it was tracking the midpoint of a single palm which was confusing.

EDIT: We could even call this `SpellSpawnLocation` or something, so it's decoupled from the way we're currently handling spell spawning.

2024-03-07 10:44 UTC, AmosHolland commented on src/spell_control.rs
> +pub struct FingerDistsClose(pub bool);
I think this could do with having a more descriptive name. Maybe something like `SpellRecognitionActive` or something, so it's not specific to the way that we're currently doing spell control, and it's more clear what's being conveyed by it (especially since it's used outside of this module, where the context makes even less sense).

2024-03-07 10:44 UTC, AmosHolland commented on src/speech.rs
> +    if config.timer.finished() && finger_dist.0 {
I think you can condense this into:
```rust
if config.timer.tick(time.delta()).just_finished() ...```

2024-03-07 10:49 UTC, AmosHolland commented on src/speech.rs
> +    mut config: ResMut<RecognitionTimer>,
Can we name this something clearer? Maybe `recognition_time`

2024-03-07 10:49 UTC, AmosHolland commented on src/speech.rs
> +        println!("detected word: {}", last_word);
Once we're confident this is working can we remove this debug print?

2024-03-07 10:52 UTC, AmosHolland commented on src/speech.rs
> +        clip.data.clear();
I don't think we should clear the data here, what if, for example, the player begins saying a spell before the timer ticks, and finishes saying it after the timer ticks - they'll have said the right spell but it might not get recognised. I think we should instead only clear the clip when a word is successfully recognised.

If making such a change breaks things then don't worry about it, this seems to be working so it's no bigs.

2024-03-07 16:41 UTC, OwenBoisse commented
added requested changes, need to test

2024-03-08 12:04 UTC, AmosHolland commented
Tested now and is working.

2024-03-08 12:06 UTC, AmosHolland approved these changes
LGTM!

2024-03-08 16:52 UTC, Foxinatel approved these changes
LGTM

2024-03-08 16:53 UTC, merged