Bomb spell
goudanough/WizARds pull request #54
Opened 2024-03-12 15:48 UTC by OwenBoisse

bomb spell
- currently hit scan
- explodes after 5 seconds dealing damage to boss if in range

2024-03-12 16:30 UTC, OwenBoisse commented on src/spells.rs
> +            commands.entity(explosion_entity).despawn();
uh kinda, if you delete it straight away it just wont detect any collisions

2024-03-12 16:34 UTC, rosefromthedead requested changes
I'd like to block this until #48 is landed

2024-03-19 10:26 UTC, AmosHolland commented on src/spells.rs
> +                    ProjectileHitEffect::Damage(DamageMask::FIRE, 25.0),
None of the changes to projectiles really affect this. Either change not to use a projectile, or make the change that amin suggested, where you make a projectile effect that doesn't despawn the projectile. Probably the latter.

2024-03-19 12:50 UTC, AmosHolland approved these changes
This looks good, nice work!

2024-03-20 09:05 UTC, AmosHolland approved these changes
LGTM!

2024-03-21 17:02 UTC, rosefromthedead approved these changes

2024-03-21 17:02 UTC, merged