Wall spell
goudanough/WizARds pull request #57
Opened 2024-03-19 13:02 UTC by OwenBoisse

creates wall behind you as you walk

2024-03-20 09:00 UTC, AmosHolland requested changes
One minor nitpick, otherwise this all looks good!

2024-03-20 09:00 UTC, AmosHolland commented on src/lib.rs
> +use bevy_hanabi::HanabiPlugin;
What's this doing here?

2024-03-20 09:04 UTC, OwenBoisse commented on src/lib.rs
> +use bevy_hanabi::HanabiPlugin;
I may have accidentally deleted the import in the effect asset branch when it was pulled into main so its missing the import for hanabi and won't run without it (unless you remove all the hanabi stuff which ig I could do in this branch)

2024-03-22 11:31 UTC, AmosHolland approved these changes
Send it!

2024-03-22 11:38 UTC, rosefromthedead approved these changes

2024-03-22 11:39 UTC, merged