setup initial networking
goudanough/WizARds pull request #6
Opened 2024-02-01 21:43 UTC by a6-webm

Untested in its final form (hence the draft pr).

Removes all instances of `#[cfg(target_os = "android")]` (can be undone, just made rust-analyzer trust me).

Adds ggrs networking with head and hands as input.

Currently IP addresses are hard coded.

Player objects are instantiated in `network.rs`, this should likely later be moved to a "player" plugin.

2024-02-02 11:04 UTC, AmosHolland requested changes
Looks good overall! Just a couple minor nitpicks / questions.

2024-02-02 11:04 UTC, AmosHolland commented on src/network.rs
> +}
Some more annotations in a couple places could be useful? Definitely read_local_inputs since that function will continue to be used, and maybe also in the player obj functions, so whoever implements the functions that replace them can use them as a reference.

2024-02-02 11:04 UTC, AmosHolland commented on src/network.rs
> +}
I definitely want to test this before we merge (as you've said), do you have any advice for how to set the headsets etc. up for testing?

2024-02-02 11:41 UTC, a6-webm commented on src/network.rs
> +}
So for the network, use someone's laptop as a hotspot (doesn't even need to provide wifi, just a network).
Connect both headsets to that network, then write down what IP each headset is.

Then on another laptop, plug in the first headset and build with `network.rs` looking like:
```rust
let args = ConnectionArgs {
    local_port: 8000,
    players: vec!["localhost".to_owned(), "<IP of 2nd headset>:8001".to_owned()],
};
```
then plug in the 2nd headset and build with `network.rs` looking like::
```rust
let args = ConnectionArgs {
    local_port: 8001,
    players: vec!["localhost".to_owned(), "<IP of 1st headset>:8000".to_owned()],
};
```
then just have both headsets be running the program at the same time and it should work.

2024-02-02 11:56 UTC, a6-webm commented on src/lib.rs
> +pub struct PlayerInput {
just added in 76d0e0f, we'll probably want to make it an enum later, but it's there for now

2024-02-05 11:08 UTC, rosefromthedead commented on src/network.rs
> +}
This worked, right? I remember testing some floating cubes, but I'm not sure if that was at this commit or an earlier one

2024-02-06 09:35 UTC, AmosHolland commented on src/network.rs
> +}
We've discussed this already but for the sake of having it documented - that was an earlier commit, additional code for sending hand positions has been added (though I'm not 100% sure if we have that working yet).

2024-02-12 10:45 UTC, rosefromthedead commented
Beautiful and pretty, thanks guys, LGTM

2024-02-12 11:02 UTC, rosefromthedead commented on src/network.rs
> +}
[11:00] Amos: if it's blocking im happy to call it quits on annotation
[11:01] Amos: would be nice to have at some point to help people with integration but not needed to make the merge

2024-02-12 11:03 UTC, AmosHolland commented on src/network.rs
> +}
This isn't necessary to allow this to merge, so I will resolve this, would still be nice to have annotations but it's not urgent.

2024-02-12 11:04 UTC, AmosHolland approved these changes
LGTM!

2024-02-12 11:10 UTC, merged