update healthbar
goudanough/WizARds pull request #65
Opened 2024-04-15 12:24 UTC by OwenBoisse

move healthbar to above boss
change to 3d oblong

2024-04-15 14:12 UTC, rosefromthedead commented on src/health_bar.rs
> +    if let Some(player_transform) = player_query.iter().next() {
could this be a let-else? and `query.iter().next()` can be `query.get_single()`

2024-04-17 09:51 UTC, rosefromthedead approved these changes
Assuming this has been tested to look cool, send it, thanks!

2024-04-17 20:22 UTC, OwenBoisse commented
currently changing healthbar system further, dont approve this pr yet

2024-04-18 10:03 UTC, OwenBoisse commented
done i think

2024-04-18 10:29 UTC, rosefromthedead approved these changes
Honestly too frazzled to comprehend this but I trust you've tested it and it looks pretty harmless

2024-04-18 13:11 UTC, a6-webm approved these changes
Approving because I need to hop on master lol

2024-04-23 10:01 UTC, a6-webm commented
Ah yeah I think this PR is possibly defunct now, because I had to cherry pick the healthbar update into [boss_state_machine](https://github.com/goudanough/WizARds/tree/boss_state_machine).

2024-04-23 19:10 UTC, Foxinatel requested changes
Going to place a block on this PR since it has been reported as potentially defunct

2024-04-24 15:33 UTC, rosefromthedead commented
Closing in favour of merging it with the rest of boss_state_machine

2024-04-24 15:33 UTC, closed without merging